version: "3.8"

services:
  chalice-test-localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      SERVICES: s3,lambda,iam,apigateway
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      DEFAULT_REGION: eu-west-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d